version: "3"
services:
  ml-app:
    build: ./ModuleML/src
    volumes:
      - ./ModuleML/src:/usr/src/MLApp
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    ports:
      - "5001:5000"
networks:
  counter-net:
    driver: bridge
