version: "3"
services:
  ml-app:
    build: ./ModuleML/src
    volumes:
      - ./ModuleML/src:/usr/src/MLApp
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    ports:
      - "5001:5000"
  web-app:
    build: ./bktel
    command: npm run watch
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./bktel:/var/www/app
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - ./mysql_data:/var/lib/mysql
networks:
  counter-net:
    driver: bridge
